---
- name: Fetch pdb70 directory from S3
  hosts: clients
  become: yes
  tasks:
    - name: Create local directory for S3 files
      ansible.builtin.file:
        path: /home/ec2-user/data/pdb70/
        state: directory

    - name: List files
      amazon.aws.aws_s3: 
        mode: list
        bucket: comp0235-ucabrz5
        prefix : pdb70
      register: listresult

    - name: Copy files
      amazon.aws.aws_s3:
        bucket: comp0235-ucabrz5
        object: '{{ item }}'
        dest: '/home/ec2-user/data/pdb70/{{ item|basename }}'
        mode: get
      with_items: '{{listresult.s3_keys}}'

