---
- name: Remove Python Packages Directory
  hosts: clients
  become: yes
  tasks:
    - name: Delete /home/ec2-user/data/python_pkgs directory
      ansible.builtin.file:
        path: /home/ec2-user/data/python_pkgs
        state: absent
