---
- name: Install Python Dependencies
  hosts: clients
  become: yes
  tasks:
    - name: Install Python Dependencies with pip
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - awscli